Fix and upgrade example app (#7)
* fix: make bootstrap script work on windows

See: https://github.com/callstack/react-native-builder-bob/commit/8bac4d4

* build: upgrade dependencies in example

 - Remove `eslint` and `@react-native-community/eslint-config` as they are
   already present in the parent project.

 - Add `babel-plugin-module-resolver` which was removed in 41f5758 to fix
   error when starting the example.

* chore: upgrade example to react native 0.64.2

Upgrade native files in example app according to React Native Upgrade Helper.

* chore: rename `blacklist to `exclusionList`

See: https://github.com/callstack/react-native-builder-bob/pull/168

* fix: use correct app name in index.js

* build: add android to example again

Add `VisionCameraImageLabelerPackage` to android in example after it
was removed in 6d4a46d.

Also:

 - Rename package folder (labeller -> labeler)

 - Complete setup steps for Reanimated 2 in `MainApplication.java`

* build: add camera permissions in example

* build: upgrade dependecies

* build: remove `buildToolsVersion`

Remove `buildToolsVersion` from `build.gradle` file, as each version of
the Android Gradle Plugin now has a default version of the build tools.

See: https://github.com/callstack/react-native-builder-bob/commit/0bfd51a

* build: use older `ndkVersion` in example

Task `react-native-vision-camera:externalNativeBuildDebug` fails when using
`ndkVersion` `22.0.7026061`, downgrade to `20.1.5948944` for now.

* feat: update example app

- Remove device type from `useCameraDevices` to return any camera device

 - Add `'worklet'` directive to frame processor and use `console.log()`

 - Import `'react-native-reanimated'` to avoid `TypeError: global.__reanimatedWorkletInit is not a function`

* chore: add `useFrameProcessor` to exhaustive deps rule

* feat: add label ui element

* build(deps): update `react-native-vision-camera` dependency